### ISSUE TITLE
Update CodaLab Home Page

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab#1335]
![codalab_homepage_mockup_v4](https://cloud.githubusercontent.com/assets/4361560/10437106/bdbcdcb2-70df-11e5-8b80-8df816141337.png)
Hi Flavio,

Based upon ongoing discussions with Percy & Isabelle, we'd like to update the Home Page as follows (also see attached):

- [ ] Update all text as shown

- [ ] Replace "Explore Worksheets" and "Explore Competitions" links with large orange buttons, as shown in the mock-up

- [ ] Remove icons

- [ ] Add Headers for "Recent Worksheets" and "Latest Competitions"

- [ ] Add a div under each one that shows most recently added Worksheets from codalab.org/worksheets and most recently added Competitions from codalab.org/competitions

Please let me know if you have any questions!

Best, -- Erick

**Comment by FlavioAlexander** [comment]
@ErickWa Since we will have two orange buttons for competitions and worksheets, Do we still need Competitions and Worksheets tabs on the navigation bar?

Best,

Flavio

**Comment by percyliang** [comment]
I think we should leave them because when you're not on the main page, I
think it's useful to be able to jump around.

Also, it isn't really the most recent worksheet and competition, but just a
random one.  So I don't think we need a separate header for that.  We can
just show a random active competition and a random worksheet (some logic on
the backend is necessary to return a worksheet).

**Comment by FlavioAlexander** [comment]
resolve in #1345
