### ISSUE TITLE
upload should trigger file upload dialog

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#1388]
Currently, when click 'Upload Bundle', we show an intermediate dialog, which has a another button that shows the file selector.  Should directly show the file selector.

Progress bar should be shown for large files?

**Comment by kashizui** [comment]
note: looks like you will need to essentially gut the functionality in `upload-modal-interface.js` and move it into `worksheet-action-bar.js:doUIAction`

**Comment by percyliang** [comment]
Maybe we want to keep a place for the progress bar?  The main thing is just
reducing the number of clicks by 2.

**Comment by kashizui** [comment]
commandeering this

**Comment by kashizui** [comment]
Looks like this is actually impossible, due to certain security features in browsers.
http://stackoverflow.com/a/21583865

Still looking for specific documentation on this, but apparently it’s impossible to open a file dialog programmatically unless it’s specifically in a click event fired by the user. Since our upload dialog is opened as a response to an AJAX call (to execute `cl upload`), we can't open a file dialog directly without additional user intervention here.

However, it is possible to open a file dialog from the "Upload bundle" button. Our options:

1. Keep the modal.
2. Only show modal when using `cl upload` command—the upload bundle button in the sidebar will open file dialog directly. (This inconsistency seems weird though.)
3. Disable the `cl upload` command for file uploads on the website, or redirect user focus to the Upload bundle button in the sidebar, which will open the file dialog directly.

**Comment by percyliang** [comment]
On Dec 5, 2015 6:13 PM, "Stephen Koo" <notifications@github.com> wrote:
>
> Looks like this is actually impossible, due to certain security features
in browsers.
> http://stackoverflow.com/a/21583865
>
> Still looking for specific documentation on this, but apparently it’s
impossible to open a file dialog programmatically unless it’s specifically
in a click event fired by the user. Since our upload dialog is opened as a
response to an AJAX call (to execute cl upload), we can't open a file
dialog directly without additional user intervention here.
>
> However, it is possible to open a file dialog from the "Upload bundle"
button. Our options:
>
> Keep the modal.
> Only show modal when using cl upload command—the upload bundle button in
the sidebar will open file dialog directly. (This inconsistency seems weird
though.)
> Disable the cl upload command for file uploads on the website, or
redirect user focus to the Upload bundle button in the sidebar, which will
open the file dialog directly.

Let's go with the last option.  I don't think people will use the cl upload
very often so maybe get rid of it.

Separately, is it possible to have enter trigger the click?  Then we just
need to focus on the button when the user presses shift-u..

**Comment by kashizui** [comment]
Enter key works! 

@percyliang Are we okay with
