### ISSUE TITLE
settings page needs to be updated

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab#880]
Currently, the settings page for the user
http://localhost:8000/my/settings/
includes a bunch of competition stuff only.

There should be basic things here like name, email, affilation (same things that are asked when the user signs up).  Make this extensible so later we can add things like a home page URL, photo/icon, etc.

**Comment by xbaro** [comment]
This part is developed on my branch. User profile was added, and a view to see user information on participants list of competitions is also started. I needed to make work the Cli to be able to create a competition and see how integrate it. Now maybe is outdated because you are working so hard, but maybe you can use some part of the code.

**Comment by adamtlord** [comment]
I added as much user information as we have, and organized the fields a little bit. The registration form currently does not include first or last name.

**Comment by Raisins** [comment]
closed dup of  #965
