### ISSUE TITLE
Enable participant submissions to be made public 

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab#893]
Feature 1.) Add a button that allows competition submitter to make their submissions available from the Leaderboard, (publicly) from panel: http://codalabtest.cloudapp.net/competitions/xxx#participate-submit_results (Where XXX is the competition number)

![image](https://cloud.githubusercontent.com/assets/4361560/6376251/a28c4634-bcd1-11e4-89e8-f4daebab582a.png)
 
Add the button to the right-hand side of this screen.

Feature 2.) Once they make their submission public, give them a "Thank you" notification.

**Comment by lr292358** [comment]
Updates:
- instead of submissions available from the leader-board, all public submissions should be available from the panel analogous to this: https://www.codalab.org/my/competition/XXX/submissions/# (reasons: to share several ones in the same time, to not share the current best-one)
- the submitted file (submission_name.zip) is a link, this address users will use in their post on the forum
We can discuss the details, e.g. a get_permalink button instead of a link.

**Comment by ErickWa** [comment]
Eric C. completed -- now in test.

**Comment by ErickWa** [comment]
Updated based on Isabelle's Test feedback

**Comment by ckcollab** [comment]
Missing piece of functionality: display modal to download submission details if it is public *on leaderboard*.
