### ISSUE TITLE
Testenv worksheets are returning 500 or no bundles after cli upgrade.

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab#935]
Most worksheets are returning 500 via the web interface but work fine to the cli.
http://codalabtest.cloudapp.net/worksheets/0x82a2b99316dc4afcb4fcfcedabaf5531/

Some worksheets show up with out bundle information. 
http://codalabtest.cloudapp.net/worksheets/0x6723881020de4869b4e52e8252e3715a/
http://codalabtest.cloudapp.net/worksheets/0x2c019976bed64859875dd0215be49d5b/

The new group_bundle_permission table is on testenv but blank. 

My local env is working correctly after upgrade. If I wcp a problem worksheet  to my local codalab web instance they also work fine. 

Looking into this.

**Comment by Raisins** [comment]
cc: @ErickWa  @percyliang

**Comment by percyliang** [comment]
The problem here is that bundles have permissions (as opposed to inheriting
permissions of the worksheets they're on), and by default they have no
permissions except to the owner.  We can fix this for now by making all
bundles public:
cl work local::
cl perm $(cl search .limit=100000 -u) public r

In case we don't have permissions, the web interface should print out the
UsageError that's thrown.

**Comment by Raisins** [comment]
Did a quick test, this doesn't seem to be an ongoing issue with new bundles and worksheets. Just previous ones and on codalab test. 

Question about this if bundles have no permissions except to the owner and worksheets are by default public wont this cause problems?

**Comment by percyliang** [comment]
When bundles are created, they inherit the permissions of the worksheet, so
by default they will all be public unless the worksheet is private.

The current state of affairs is only due to the fact that these bundles
were created before bundles had permissions, so this should not be an issue
moving forward.
