### ISSUE TITLE
Worksheet bugs!

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab#954]
When using keyboard shortcuts to open the "fig" worksheet, I get the following:

![image](https://cloud.githubusercontent.com/assets/4361560/7127571/ffd820e4-e1fa-11e4-850d-ecd256131869.png)

**Comment by ErickWa** [comment]
Also, when opening "abc", "auto-ml-challenge" and "corenlp", we get 500 errors:

![image](https://cloud.githubusercontent.com/assets/4361560/7127601/33054d84-e1fb-11e4-9803-e54493f3b03f.png)

**Comment by ErickWa** [comment]
Same with the VW worksheet, which is an important one!

**Comment by Raisins** [comment]
Hey Erick, 

The 2 errors are due to issue #935 from before since those are @percyliang  worksheets and I do not have access. @percyliang can you run your fix on testenv worksheets from the other ticket to fix legacy permission errors
`PermissionError: User francis does not have sufficient permissions on bundle 0xec44......b7 (have none, need read).`

-----
The top error of 404 is a bug, will push a fix.

**Comment by percyliang** [comment]
@Francis: I can do that, but we should also make the the web interface show
a meaningful error when there is one.

**Comment by francis** [comment]
Hi Percy,

I'm afraid you have the wrong Francis here.

Thanks,
Francis

---
