### ISSUE TITLE
Scoring program access to all entries

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#957]
This is an issue related to:
https://github.com/codalab/codalab/issues/908

To implement coopetitions, we need to be able to compare entries with one another. In particular, one index of novelty of an entry is the number of errors that are in common with other entries: if there are few errors and there is a low overlap between these errors and other entries' errors, the new entry has a lot of added value.

To compute differences in errors made by the participants, the scoring program needs access to all the entries made, not just the user's entry.

**Comment by ckcollab** [comment]
Still waiting on @lr292358 to test this

**Comment by lr292358** [comment]
The reply is in the #1032

**Comment by ckcollab** [comment]
Scoring program output may be lost? Try "-u" flag?

**Comment by lr292358** [comment]
Adding -u didn't change too much (instead of nothing, an initial part of stdout was stored).
I added sleep 6 seconds at the end of the script and how works good, so OK.

But in general output of users codes/runtime errors before crash might not be stored, so this is still an issue --> I created a new one for it #1047, and I close this one.

**Comment by ckcollab** [comment]
Thanks for the blazing fast feedback @lr292358! :)
